// =============================================================================
// Host keyboard layout overlay
// =============================================================================
// A `HostLayout` is a thin per-HID override on top of `src/keycodes.ts`.
// It changes what we *label* a key as, not the HID code that gets sent.
// (ZMK firmware speaks HID; the host OS turns that into a character based
// on its own layout. If you set Studio's host layout to JIS, you're telling
// Studio "show me labels that match what my OS will type" — bindings stay
// the same.)
//
// Adding a layout:
//   1. Drop a `<lang>.ts` exporting a `Map<hidCode, Partial<...>>`.
//      Most files are generated by `scripts/import-layouts.py` from
//      upstream QMK keymap_<lang>.h-style sources; hand-written files
//      (ko, jis additions) live alongside them.
//   2. Add it to `LAYOUTS` below. The picker, the keycap renderer, and
//      the dropdown in AppHeader pick it up automatically.
// =============================================================================

import type { Keycode } from "../keycodes";

// Hand-written layouts
import { JIS_OVERRIDES } from "./jis";
import { KO_OVERRIDES } from "./ko";

// Generated layouts (run `python scripts/import-layouts.py` to refresh)
import { EN_UK_OVERRIDES } from "./en-uk";
import { US_INTL_OVERRIDES } from "./us-intl";
import { EN_CA_OVERRIDES } from "./en-ca";
import { DE_OVERRIDES } from "./de";
import { FR_OVERRIDES } from "./fr";
import { ES_OVERRIDES } from "./es";
import { ES_LATAM_OVERRIDES } from "./es-latam";
import { IT_OVERRIDES } from "./it";
import { PT_OVERRIDES } from "./pt";
import { PT_BR_OVERRIDES } from "./pt-br";
import { SV_OVERRIDES } from "./sv";
import { NO_OVERRIDES } from "./no";
import { DA_OVERRIDES } from "./da";
import { CH_OVERRIDES } from "./ch";
import { PL_OVERRIDES } from "./pl";
import { HU_OVERRIDES } from "./hu";
import { SK_OVERRIDES } from "./sk";
import { HR_OVERRIDES } from "./hr";
import { TR_OVERRIDES } from "./tr";
import { EURKEY_OVERRIDES } from "./eurkey";

/**
 * Per-HID label overrides. Only the fields that DIFFER from the base SSOT
 * need to be listed; missing fields fall back to the base row.
 */
export type LayoutOverride = Partial<Pick<Keycode, "short" | "med" | "long">>;

export type LayoutOverrideMap = ReadonlyMap<number, LayoutOverride>;

/**
 * Physical-keyboard family this layout's users are typically on. Drives
 * what shape the picker's ISO/JIS tab renders. Most layouts split cleanly:
 * Europe / UK / ANZ uses ISO, Japan uses JIS, Korea uses an ANSI-with-
 * IME-extras variant, US uses plain ANSI.
 */
export type PhysicalFamily = "ansi" | "iso" | "jis" | "ko";

export interface HostLayout {
  /** Stable ID used in localStorage. Don't change after release. */
  id: string;
  /** Human-readable name for the picker (native script + English). */
  name: string;
  /** Per-HID overrides; empty for the identity (US ANSI = base SSOT). */
  overrides: LayoutOverrideMap;
  /** Physical keyboard family (drives picker ISO/JIS tab shape). */
  physical: PhysicalFamily;
}

export const US_ANSI_LAYOUT: HostLayout = {
  id: "us-ansi",
  name: "English (US ANSI)",
  overrides: new Map(),
  physical: "ansi",
};

export const JIS_LAYOUT: HostLayout = {
  id: "jis",
  name: "日本語 (Japanese)",
  overrides: JIS_OVERRIDES,
  physical: "jis",
};

export const KO_LAYOUT: HostLayout = {
  id: "ko",
  name: "한국어 (Korean)",
  overrides: KO_OVERRIDES,
  physical: "ko",
};

// Layouts are listed in roughly geographic / script grouping so the
// dropdown is scannable: ANSI baseline, then CJK, then English variants,
// then Western Europe, Iberian / Latin America, Northern Europe, Central
// Europe, and finally pan-European specialty layouts.
export const LAYOUTS: ReadonlyArray<HostLayout> = [
  US_ANSI_LAYOUT,
  JIS_LAYOUT,
  KO_LAYOUT,
  // Canadian CSA, US International keep the ANSI physical form.
  { id: "en-ca",    name: "English (Canadian CSA)",     overrides: EN_CA_OVERRIDES,    physical: "ansi" },
  { id: "us-intl",  name: "English (US International)", overrides: US_INTL_OVERRIDES,  physical: "ansi" },
  // Everyone else on this list is ISO-physical in the wild.
  { id: "en-uk",    name: "English (UK)",               overrides: EN_UK_OVERRIDES,    physical: "iso" },
  { id: "de",       name: "Deutsch (German)",           overrides: DE_OVERRIDES,       physical: "iso" },
  { id: "fr",       name: "Français (French)",          overrides: FR_OVERRIDES,       physical: "iso" },
  { id: "es",       name: "Español (Spanish)",          overrides: ES_OVERRIDES,       physical: "iso" },
  { id: "es-latam", name: "Español (Latinoamericano)",  overrides: ES_LATAM_OVERRIDES, physical: "iso" },
  { id: "it",       name: "Italiano (Italian)",         overrides: IT_OVERRIDES,       physical: "iso" },
  { id: "pt",       name: "Português (Portuguese)",     overrides: PT_OVERRIDES,       physical: "iso" },
  { id: "pt-br",    name: "Português (Brasileiro)",     overrides: PT_BR_OVERRIDES,    physical: "iso" },
  { id: "sv",       name: "Svenska (Swedish)",          overrides: SV_OVERRIDES,       physical: "iso" },
  { id: "no",       name: "Norsk (Norwegian)",          overrides: NO_OVERRIDES,       physical: "iso" },
  { id: "da",       name: "Dansk (Danish)",             overrides: DA_OVERRIDES,       physical: "iso" },
  { id: "ch",       name: "Schweiz / Suisse (Swiss)",   overrides: CH_OVERRIDES,       physical: "iso" },
  { id: "pl",       name: "Polski (Polish)",            overrides: PL_OVERRIDES,       physical: "iso" },
  { id: "hu",       name: "Magyar (Hungarian)",         overrides: HU_OVERRIDES,       physical: "iso" },
  { id: "sk",       name: "Slovenský (Slovak)",         overrides: SK_OVERRIDES,       physical: "iso" },
  { id: "hr",       name: "Hrvatski (Croatian)",        overrides: HR_OVERRIDES,       physical: "iso" },
  { id: "tr",       name: "Türkçe (Turkish)",           overrides: TR_OVERRIDES,       physical: "iso" },
  { id: "eurkey",   name: "EurKey",                     overrides: EURKEY_OVERRIDES,   physical: "iso" },
];

export const DEFAULT_LAYOUT_ID = US_ANSI_LAYOUT.id;

export function getLayoutById(id: string | null | undefined): HostLayout {
  if (!id) return US_ANSI_LAYOUT;
  return LAYOUTS.find((l) => l.id === id) ?? US_ANSI_LAYOUT;
}
